document.write('<link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous"><div class="footer-alert" id="don" style="font-family: &quot;Roboto&quot;, sans-serif;padding-top: 5px;padding-bottom: 5px;position: fixed;bottom: 10px;left: 200%;transform: translateX(-50%);width: 90%;background-color: #fff;padding-right: 20px;box-shadow: 0 5px 20px rgba(0, 0, 0, 0.15);transition: 0.5s;"><button class="close" type="button" onclick="myFunction()" style="padding: 0;border: none;position: absolute;font-size: 15px;text-align: center;right: 0;top: 0;width: 20px;background-color: lightgray;height: 100%;line-height: 63px;"><i class="fas fa-times" style="-moz-osx-font-smoothing: grayscale;-webkit-font-smoothing: antialiased;display: inline-block;font-style: normal;font-variant: normal;text-rendering: auto;line-height: 1;font-family: &quot;Font Awesome 5 Free&quot;;font-weight: 900;"></i></button><div class="media" style="display: flex;align-items: flex-start;"><img src="https://raw.githubusercontent.com/alltimehasan/cdn-images.github.io/master/gmail.png" style="width: 54px;height: 54px;"><div class="media-body"><p style="margin: 0;padding: 0;font-size: 15px;line-height: 18px;padding-left: 8px;font-family: &quot;Roboto&quot;, sans-serif;"><strong>Lorem ipsum</strong><br>dolor sit amet, Lorem ipsum consectetur adipisicing elit.<i class="fas fa-gift" style="-moz-osx-font-smoothing: grayscale;-webkit-font-smoothing: antialiased;display: inline-block;font-style: normal;font-variant: normal;text-rendering: auto;line-height: 1;font-family: &quot;Font Awesome 5 Free&quot;;font-weight: 900;color: tomato;"></i></p></div></div></div>');


window.onload = function() {don();};
function don() {
    document.getElementById('don').style.left = '50%';
}
function myFunction() {
    document.getElementById('don').style.left = '200%'
}